name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Run unit tests and generate HTML report
        run: npm run test:unit

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: jest-html-report
          path: unit-test-report.html
